export const ACTION_TYPE = {
  ACTION_TYPE: "ACTION_TYPE",
  STORE_DATA_FROM_MASTER_DATA: "STORE_DATA_FROM_MASTER_DATA",
  SET_PAGE_REDUX_DATA: "SET_PAGE_REDUX_DATA",
  SET_ROW_PER_PAGE_REDUX_DATA: "SET_ROW_PER_PAGE_REDUX_DATA",
  SET_CART_ITEM_REDUX_DATA: "SET_CART_ITEM_REDUX_DATA",
};
